drive stuff but for real now
recordrobotics/2023_Control pull request #5
Opened 2023-01-20 01:56 UTC by DragonSM

2023-01-20 23:58 UTC, fielia requested changes
one minor thing, but the rest is jut copy-paste. i think the rest is good.

2023-01-20 23:58 UTC, fielia commented on README.md
> +_LStick_; _Joystick for robot motion_
I don't think you need the underscores

2023-01-21 15:48 UTC, vladaviedov commented on src/main/java/org/recordrobotics/charger/RobotContainer.java
> +	 * Create teleop commands
This function activates the commands, it doesn't create them

2023-01-21 20:21 UTC, fielia submitted a review, later dismissed

2023-01-21 20:28 UTC, fielia approved these changes

2023-01-22 01:59 UTC, vladaviedov approved these changes

2023-01-24 03:01 UTC, merged